source "http://rubygems.org"

gem "sinatra"
gem "resque"
gem "json"
gem "mongo_mapper"
gem "bson_ext"
gem "tilt", "1.3.2"
gem "oauth"
gem 'nestful', "0.0.6"
gem 'activesupport', "3.0.9"
gem 'actionpack', "3.0.9"
gem 'actionmailer', "3.0.9"
